daftarKata = [
"Boolean algebra",
"Euclidean algorithm",
"Fourier series",
"Galois group",
"Grothendieck topos",
"Kleisli category",
"Laurent series",
"Lie algebra",
"Lie algebroid",
"Lie bracket",
"Lie groupoid",
"Maclaurin series",
"Noetherian scheme",
"Taylor series",
"Yoneda lemma",
"abelian category",
"abelian group",
"abscissa",
"absolute value",
"absolutely convergent series",
"acnode",
"acute angle",
"addition",
"additive category",
"adherence",
"adjacent angle",
"adjoint",
"affine scheme",
"affix",
"algebra",
"algebraic group",
"algebraic variety",
"algebraically closed field",
"algorithm",
"alternating series",
"analytic set",
"angle",
"antecedent",
"antilogarithm",
"apothem",
"arc",
"area",
"argument",
"arithmetic",
"asymmetry",
"asymptote",
"axiom",
"axis",
"axonometry",
"barycenter",
"base",
"bijective correspondence",
"bijective function",
"binomial",
"blow-up",
"bound",
"boundary",
"boundary operator",
"bundle",
"cartesian category",
"cartesian product",
"category",
"central angle",
"chain",
"chain complex",
"character",
"class",
"clopen set",
"closed set",
"closure",
"coboundary",
"coboundary operator",
"cochain",
"cochain complex",
"cocomplete category",
"cofibration",
"cofinal set",
"coherent sheaf",
"cohomology",
"colimit",
"commutative group",
"commutative ring",
"compact manifold",
"compactification",
"complementary angle",
"complementary set",
"complete category",
"complex number",
"composition series",
"cone",
"connected manifold",
"connected scheme",
"consequent",
"continuous function",
"contradiction",
"convergent series",
"coordinate axis",
"correspondence",
"countable set",
"cover",
"covering space",
"curve",
"cyclic group",
"decahedron",
"definable set",
"derivative",
"derived category",
"diagonal matrix",
"differentiable function",
"differential",
"dihedral angle",
"dimension",
"direct limit",
"direct sum",
"distribution",
"division ring",
"eigenvalue",
"eigenvector",
"element",
"embedding",
"empty set",
"equality",
"equivalence",
"even number",
"exponent",
"exponentiation",
"exterior algebra",
"face",
"factor",
"fibration",
"fibre",
"fibre bundle",
"field",
"finite field",
"finite group",
"finite set",
"finitely generated algebra",
"finitely generated module",
"finitely presentable category",
"free algebra",
"free module",
"full subcategory",
"function",
"functor",
"genus",
"gerbe",
"greatest lower bound",
"group",
"group representation",
"group ring",
"group scheme",
"groupoid",
"height",
"heterogenous algebra",
"holomorphic function",
"homology",
"homomorphism",
"homotopy",
"homotopy category",
"homotopy class",
"homotopy equivalence",
"homotopy fiber",
"homotopy type",
"identity element",
"imaginary axis",
"infimum",
"infinite set",
"injective function",
"injective module",
"inscribed angle",
"integral scheme",
"inverse element",
"inverse limit",
"irreducible representation",
"irreducible scheme",
"lattice",
"least upper bound",
"left adjoint",
"limit",
"linear algebraic group",
"linear function",
"locally Noetherian scheme",
"locally finitely presentable category",
"locally ringed space",
"logarithm",
"lower bound",
"manifold",
"map",
"mapping cone",
"mapping cylinder",
"matrix",
"maximum",
"measurable set",
"member",
"minimum",
"model category",
"module",
"moduli space",
"monad",
"monoid",
"monotone function",
"morphism",
"multiple",
"multiplicand",
"multiplication",
"multiplier",
"natural number",
"natural transformation",
"negative number",
"neutral element",
"non-empty set",
"noncommutative ring",
"normal group",
"normal scheme",
"null matrix",
"number",
"numeric value",
"obtuse angle",
"odd number",
"open cover",
"open set",
"operad",
"opposite angle",
"orbifold",
"ordered pair",
"partial derivative",
"partial function",
"partially ordered set",
"perfect field",
"polynomial",
"positive number",
"power",
"power series",
"presheaf",
"product",
"projective module",
"projective set",
"proof",
"proof by contradiction",
"pullback",
"pushout",
"quasi-coherent sheaf",
"quasi-compact scheme",
"quasi-isomorphism",
"rational number",
"real axis",
"real number",
"reduced group",
"reduced scheme",
"reductive group",
"reflective subcategory",
"relation",
"representation",
"right adjoint",
"right angle",
"ring",
"ringed space",
"scheme",
"scheme of finite type",
"semisimple module",
"separated scheme",
"series",
"set",
"sheaf",
"similarity",
"simple module",
"simplex category",
"simplicial complex",
"simplicial set",
"simplicial space",
"singularity",
"sketch",
"skew field",
"small category",
"smooth manifold",
"solid angle",
"square matrix",
"stationary set",
"subcategory",
"subspace",
"sum",
"supplementary angle",
"supremum",
"surface",
"surjective function",
"symmetric algebra",
"symmetry",
"tensor algebra",
"tensor product",
"term algebra",
"tiling",
"topological space",
"topology",
"topos",
"trace",
"transitive set",
"transpose matrix",
"triangular matrix",
"triangulated category",
"trihedral angle",
"uncountable set",
"union",
"upper bound",
"value",
"variable",
"variance",
"vector",
"vector bundle",
"vector space",
"volume",
"weak homotopy equivalence",
"width",
"zero matrix",
  "0",
  "1",
  "10-polytopes",
  "3-manifolds",
  "4-manifolds",
  "5-polytopes",
  "6-polytopes",
  "7-polytopes",
  "8-polytopes",
  "9-polytopes",
  "Abelian group theory",
  "Abelian varieties",
  "Abstract algebra",
  "Additive categories",
  "Additive number theory",
  "Adjoint functors",
  "Affine geometry",
  "Algebra",
  "Algebra stubs",
  "Algebraic K-theory",
  "Algebraic analysis",
  "Algebraic combinatorics",
  "Algebraic curves",
  "Algebraic geometry",
  "Algebraic graph theory",
  "Algebraic groups",
  "Algebraic homogeneous spaces",
  "Algebraic logic",
  "Algebraic number theory",
  "Algebraic numbers",
  "Algebraic structures",
  "Algebraic surfaces",
  "Algebraic topology",
  "Algebraic varieties",
  "Algebras",
  "Algorithmic information theory",
  "Analysis of variance",
  "Analytic geometry",
  "Analytic number theory",
  "Ancient Greek mathematical works",
  "Ancient Roman mathematics",
  "Application-specific graphs",
  "Applied mathematics",
  "Applied mathematics stubs",
  "Applied probability",
  "Approximation theory",
  "Approximations",
  "Arbelos",
  "Archimedean solids",
  "Area",
  "Arithmetic",
  "Arithmetic functions",
  "Arithmetic problems of plane geometry",
  "Arithmetic problems of solid geometry",
  "Asymptotic analysis",
  "Automated theorem proving",
  "Automorphic forms",
  "Axiom of choice",
  "Axioms of set theory",
  "Babylonian mathematics",
  "Banach algebras",
  "Banach spaces",
  "Base-dependent integer sequences",
  "Basic concepts in infinite set theory",
  "Basic concepts in set theory",
  "Bayesian statistics",
  "Bifurcation theory",
  "Bilinear forms",
  "Bilinear maps",
  "Binary operations",
  "Binary polyhedral groups",
  "Biographies and autobiographies of mathematicians",
  "Biorthogonal wavelets",
  "Bipyramids",
  "Birational geometry",
  "Boolean algebra",
  "Boundary conditions",
  "Braid groups",
  "C*-algebras",
  "Calculus",
  "Calculus of variations",
  "Capacity-approaching codes",
  "Cardinal numbers",
  "Catalan solids",
  "Categorical data",
  "Categorical logic",
  "Category theory",
  "Category theory stubs",
  "Categories in category theory",
  "Chaos theory",
  "Chaotic maps",
  "Characteristic classes",
  "Characterization of probability distributions",
  "Chinese mathematics",
  "Chiral polyhedra",
  "Circle packing",
  "Circles",
  "Circuit complexity",
  "Class field theory",
  "Classes of prime numbers",
  "Classical geometry",
  "Clifford algebras",
  "Closed categories",
  "Closure operators",
  "Coalgebras",
  "Coding theory",
  "Cohomology theories",
  "Combinatorial algorithms",
  "Combinatorial design",
  "Combinatorial game theory",
  "Combinatorial group theory",
  "Combinatorial optimization",
  "Combinatorics",
  "Combinatorics on words",
  "Combinatorics stubs",
  "Combinatory logic",
  "Commutative algebra",
  "Compactification (mathematics)",
  "Compactness (mathematics)",
  "Compactness theorems",
  "Comparison of assessments",
  "Complex analysis",
  "Complex manifolds",
  "Complex numbers",
  "Complex surfaces",
  "Complexity classes",
  "Computational complexity theory",
  "Computational geometry",
  "Computational group theory",
  "Computational hardness assumptions",
  "Computational number theory",
  "Computational problems in graph theory",
  "Computational resources",
  "Computational statistics",
  "Computational statistics journals",
  "Computational topology",
  "Computer algebra",
  "Computer arithmetic algorithms",
  "Configurations (geometry)",
  "Conformal geometry",
  "Conformal mappings",
  "Conic sections",
  "Conjectures",
  "Conjectures about prime numbers",
  "Connection (mathematics)",
  "Constructible universe",
  "Constructivism (mathematics)",
  "Continued fractions",
  "Continuous distributions",
  "Continuous wavelets",
  "Continuum theory",
  "Convergence tests",
  "Convex analysis",
  "Convex geometry",
  "Coordinate systems",
  "Coordinate systems in differential geometry",
  "Covariance and correlation",
  "Covering lemmas",
  "Coxeter groups",
  "Curvature (mathematics)",
  "Curves",
  "Cyclotomic fields",
  "Dagger categories",
  "Decision-making paradoxes",
  "Definitions of mathematical integration",
  "Deltahedra",
  "Descriptive complexity",
  "Descriptive set theory",
  "Determinacy",
  "Determinants",
  "Diagram algebras",
  "Diffeomorphisms",
  "Differential algebra",
  "Differential calculus",
  "Differential equations",
  "Differential forms",
  "Differential geometry",
  "Differential geometry of surfaces",
  "Differential operators",
  "Differential structures",
  "Differential systems",
  "Differential topology",
  "Differentiation rules",
  "Digital topology",
  "Dimension",
  "Dimension theory",
  "Diophantine approximation",
  "Diophantine equations",
  "Diophantine geometry",
  "Directed graphs",
  "Discrete distributions",
  "Discrete geometry",
  "Discrete groups",
  "Discrete mathematics",
  "Disproved conjectures",
  "Divergent series",
  "Division (mathematics)",
  "Divisor function",
  "Domain decomposition methods",
  "Domain theory",
  "Duality theories",
  "Dynamic programming",
  "Dynamical systems",
  "Effective descriptive set theory",
  "Egyptian fractions",
  "Egyptian mathematics",
  "Elementary algebra",
  "Elementary arithmetic",
  "Elementary geometry",
  "Elementary mathematics",
  "Elementary number theory",
  "Elementary special functions",
  "Elliptic curves",
  "Elliptic functions",
  "Elliptic partial differential equations",
  "Empirical process",
  "Enumerative combinatorics",
  "Equations of fluid dynamics",
  "Ergodic theory",
  "Euclidean geometry",
  "Euclidean plane geometry",
  "Euclidean solid geometry",
  "Euclidean symmetries",
  "Experimental mathematics",
  "Exponentials",
  "Extensions and generalizations of graphs",
  "F-divergences",
  "FFT algorithms",
  "Factorial and binomial topics",
  "Faculty of Mathematics, University of Cambridge",
  "Families of sets",
  "Fiber bundles",
  "Fibonacci numbers",
  "Field extensions",
  "Field (mathematics)",
  "Fields of mathematics",
  "Figurate numbers",
  "Finite differences",
  "Finite fields",
  "Finite geometry",
  "Finite groups",
  "Finite model theory",
  "Finite reflection groups",
  "Finite rings",
  "Finsler geometry",
  "First order methods",
  "Fixed points",
  "Foliations",
  "Forcing",
  "Formal systems",
  "Formal theories of arithmetic",
  "Fourier analysis",
  "Fourier series",
  "Fractal curves",
  "Fractals",
  "Fractional calculus",
  "Fractions (mathematics)",
  "Fredholm theory",
  "Free algebraic structures",
  "Free probability theory",
  "French mathematical seminars",
  "Functional analysis",
  "Functional calculus",
  "Functional equations",
  "Functional subgroups",
  "Functions and mappings",
  "Functors",
  "Galois theory",
  "Gambling mathematics",
  "Gamma and related functions",
  "General topology",
  "Generalizations of the derivative",
  "Generalized functions",
  "Generalized manifolds",
  "Generating functions",
  "Geometric algebra",
  "Geometric algorithms",
  "Geometric flow",
  "Geometric graph theory",
  "Geometric graphs",
  "Geometric group theory",
  "Geometric shapes",
  "Geometric topology",
  "Geometry",
  "Geometry of divisors",
  "Geometry of numbers",
  "Geometry stubs",
  "Glossaries of mathematics",
  "Golden ratio",
  "Graph algorithms",
  "Graph coloring",
  "Graph connectivity",
  "Graph enumeration",
  "Graph families",
  "Graph invariants",
  "Graph operations",
  "Graph products",
  "Graph theory",
  "Graph theory objects",
  "Graphical concepts in set theory",
  "Graphical models",
  "Graphical projections",
  "Graphs",
  "Greek mathematics",
  "Group actions",
  "Group automorphisms",
  "Group theory",
  "Hardy spaces",
  "Harmonic analysis",
  "Harmonic functions",
  "Hierarchy of functions",
  "Higher category theory",
  "Hilbert spaces",
  "Hilbert's problems",
  "Historical treatment of quaternions",
  "History of logic",
  "History of mathematics",
  "Hodge theory",
  "Homeomorphisms",
  "Homogeneous polynomials",
  "Homogeneous spaces",
  "Homological algebra",
  "Homology theory",
  "Homotopy theory",
  "Honeycombs (geometry)",
  "Hopf algebras",
  "Hyperbolic geometry",
  "Hyperbolic partial differential equations",
  "Hypercomplex numbers",
  "Hypergeometric functions",
  "Hypergraphs",
  "Ideals (ring theory)",
  "Incidence geometry",
  "Independence (probability theory)",
  "Independence results",
  "Indian mathematics",
  "Individual graphs",
  "Infinite graphs",
  "Infinite group theory",
  "Infinity",
  "Inner model theory",
  "Integer factorization algorithms",
  "Integer sequences",
  "Integers",
  "Integrable systems",
  "Integral calculus",
  "Integral equations",
  "Integral geometry",
  "Integral transforms",
  "Integrals",
  "Integration on manifolds",
  "International Mathematical Olympiad",
  "Interpolation",
  "Intersection classes of graphs",
  "Intersection theory",
  "Invariant subspaces",
  "Invariant theory",
  "Inverse functions",
  "Inverse problems",
  "Inversive geometry",
  "Irrational numbers",
  "Isomorphism theorems",
  "Japanese mathematics",
  "Johnson solids",
  "K-theory",
  "Kepler–Poinsot polyhedra",
  "Knot theory",
  "Lambda calculus",
  "Large cardinals",
  "Large integers",
  "Large numbers",
  "Latin squares",
  "Lattice points",
  "Lattice theory",
  "Least squares",
  "Lemmas",
  "Lie algebras",
  "Lie groupoids",
  "Lie groups",
  "Limit sets",
  "Limits",
  "Limits",
  "Linear algebra",
  "Linear operators",
  "Linear operators in calculus",
  "Linear programming",
  "Lipschitz maps",
  "Lists of mathematicians",
  "Lists of things named after mathematicians",
  "Localization (mathematics)",
  "Logarithms",
  "Logic books",
  "Logical calculi",
  "Logical connectives",
  "Lorentzian manifolds",
  "Low-dimensional topology",
  "Low-discrepancy sequences",
  "Magic squares",
  "Manifolds",
  "Map projections",
  "Maps of manifolds",
  "Markov chain Monte Carlo",
  "Markov models",
  "Markov networks",
  "Martingale theory",
  "Matching (graph theory)",
  "Mathematical analysis",
  "Mathematical analysis stubs",
  "Mathematical axioms",
  "Mathematical chairs",
  "Mathematical concepts",
  "Mathematical congresses",
  "Mathematical constants",
  "Mathematical databases",
  "Mathematical examples",
  "Mathematical games",
  "Mathematical identities",
  "Mathematical institutes",
  "Mathematical logic",
  "Mathematical logic hierarchies",
  "Mathematical logic organizations",
  "Mathematical logic stubs",
  "Mathematical modeling",
  "Mathematical notation",
  "Mathematical objects",
  "Mathematical optimization",
  "Mathematical paradoxes",
  "Mathematical physics",
  "Mathematical principles",
  "Mathematical problems",
  "Mathematical proofs",
  "Mathematical relations",
  "Mathematical science occupations",
  "Mathematical societies",
  "Mathematical structures",
  "Mathematical symbols",
  "Mathematical tables",
  "Mathematical terminology",
  "Mathematical theorems",
  "Mathematical tools",
  "Mathematics",
  "Mathematics and culture",
  "Mathematics awards",
  "Mathematics books",
  "Mathematics competition stubs",
  "Mathematics competitions",
  "Mathematics conferences",
  "Mathematics disambiguation pages",
  "Mathematics education",
  "Mathematics education reform",
  "Mathematics education television series",
  "Mathematics fiction books",
  "Mathematics in the medieval Islamic world",
  "Mathematics journals",
  "Mathematics literature",
  "Mathematics literature stubs",
  "Mathematics manuscripts",
  "Mathematics of computing",
  "Mathematics of rigidity",
  "Mathematics organizations",
  "Mathematics papers",
  "Mathematics stubs",
  "Mathematics templates",
  "Mathematics timelines",
  "Mathematics websites",
  "Mathematics-related lists",
  "Matrix decompositions",
  "Matrix normal forms",
  "Matrix theory",
  "Matroid theory",
  "Means",
  "Measure theory",
  "Measures (measure theory)",
  "Measures (set theory)",
  "Mental calculation",
  "Metatheorems",
  "Metric geometry",
  "Millennium Prize Problems",
  "Minimal surfaces",
  "Misuse of statistics",
  "Model theory",
  "Modular arithmetic",
  "Modular forms",
  "Module theory",
  "Moduli theory",
  "Monoidal categories",
  "Monte Carlo methods",
  "Moonshine theory",
  "Morphisms",
  "Morphisms of schemes",
  "Morse theory",
  "Multi-dimensional geometry",
  "Multilinear algebra",
  "Multiple comparisons",
  "Multiplication",
  "Multiplicative functions",
  "Multivariable calculus",
  "Multivariate continuous distributions",
  "Multivariate discrete distributions",
  "Multivariate interpolation",
  "Multivariate statistics",
  "Network flow problem",
  "Nilpotent groups",
  "Non-associative algebra",
  "Non-associative algebras",
  "Non-Euclidean geometry",
  "Non-Newtonian calculus",
  "Non-classical logic",
  "Non-parametric Bayesian methods",
  "Non-parametric statistics",
  "Nonstandard analysis",
  "Non-standard positional numeral systems",
  "Non-uniform random numbers",
  "Noncommutative geometry",
  "Nonconvex polyhedra",
  "Nonlinear functional analysis",
  "Nonlinear systems",
  "Nonparametric regression",
  "Normal forms (logic)",
  "Normality tests",
  "Normed spaces",
  "Norms (mathematics)",
  "Number stubs",
  "Number theoretic algorithms",
  "Number theory",
  "Number theory stubs",
  "Numbers",
  "Numeral systems",
  "Numerals",
  "Numerical analysis",
  "Numerical differential equations",
  "Numerical linear algebra",
  "Objects (category theory)",
  "Octonions",
  "Operator algebras",
  "Operator theory",
  "Optimization algorithms and methods",
  "Order theory",
  "Ordered algebraic structures",
  "Ordered groups",
  "Ordinal numbers",
  "Ordinary differential equations",
  "Orthogonal polynomials",
  "Orthogonal wavelets",
  "P-groups",
  "Parabolic partial differential equations",
  "Paradoxes of naive set theory",
  "Parametric families of graphs",
  "Parametric statistics",
  "Partial differential equations",
  "Partial fractions",
  "Particle statistics",
  "Perfect graphs",
  "Permutation groups",
  "Permutations",
  "Perturbation theory",
  "Philosophy of mathematics",
  "Pi",
  "Pi algorithms",
  "Platonic solids",
  "Point processes",
  "Poisson point processes",
  "Poker probability",
  "Polish mathematics",
  "Polychora",
  "Polyforms",
  "Polygons",
  "Polyhedra",
  "Polyhedral combinatorics",
  "Polyhedral compounds",
  "Polyhedral stellation",
  "Polyhedron stubs",
  "Polynomials",
  "Polytopes",
  "Positional numeral systems",
  "Potential theory",
  "Predicate logic",
  "Primality tests",
  "Prime numbers",
  "Prismatoid polyhedra",
  "Probabilistic complexity classes",
  "Probabilistic inequalities",
  "Probability",
  "Probability and statistics",
  "Probability assessment",
  "Probability distributions",
  "Probability interpretations",
  "Probability stubs",
  "Probability theory",
  "Probability theory paradoxes",
  "Projective geometry",
  "Projective polyhedra",
  "Proof theory",
  "Properties of Lie algebras",
  "Properties of groups",
  "Properties of topological spaces",
  "Propositional calculus",
  "Pseudoprimes",
  "Pyramids (geometry)",
  "Q-analogs",
  "Quadratic forms",
  "Quadratic residue",
  "Quadrics",
  "Quadrilaterals",
  "Quantification (science)",
  "Quantum Monte Carlo",
  "Quantum complexity theory",
  "Quantum groups",
  "Quasiregular polyhedra",
  "Quaternions",
  "Ramsey theory",
  "Random dynamical systems",
  "Random graphs",
  "Random matrices",
  "Randomized algorithms",
  "Rational functions",
  "Rational numbers",
  "Real algebraic geometry",
  "Real analysis",
  "Real closed field",
  "Real numbers",
  "Recreational mathematics",
  "Recurrence relations",
  "Reflection groups",
  "Regression analysis",
  "Regression variable selection",
  "Regular graphs",
  "Regular polyhedra",
  "Representable functors",
  "Representation theory",
  "Representation theory of Lie algebras",
  "Representation theory of Lie groups",
  "Representation theory of algebraic groups",
  "Representation theory of finite groups",
  "Representation theory of groups",
  "Riemann surfaces",
  "Riemannian geometry",
  "Ring theory",
  "Root-finding algorithms",
  "Rotation in three dimensions",
  "Rules of inference",
  "Runge–Kutta methods",
  "Sampling (statistics)",
  "Sampling techniques",
  "Scheme theory",
  "Schools of mathematics",
  "Self-dual polyhedra",
  "Semigroup theory",
  "Separation axioms",
  "Sequences and series",
  "Sequential methods",
  "Series of mathematics books",
  "Set theory",
  "Set theory stubs",
  "Set-theoretic universes",
  "Sets of real numbers",
  "Several complex variables",
  "Sextic curves",
  "Sheaf theory",
  "Sieve theory",
  "Simplicial sets",
  "Singular integrals",
  "Singular value decomposition",
  "Singularity theory",
  "Smooth functions",
  "Sobolev spaces",
  "Solitons",
  "Solvable groups",
  "Space-filling polyhedra",
  "Sparse matrices",
  "Special functions",
  "Special hypergeometric functions",
  "Spectral sequences",
  "Spectral theory",
  "Spherical trigonometry",
  "Spirals",
  "Spiric sections",
  "Splines (mathematics)",
  "Sporadic groups",
  "Stability theory",
  "Statistical algorithms",
  "Statistical awards",
  "Statistical deviation and dispersion",
  "Statistical distance",
  "Statistical hypothesis testing",
  "Statistical inequalities",
  "Statistical laws",
  "Statistical methods",
  "Statistical paradoxes",
  "Statistical randomness",
  "Statistical tests",
  "Statistical theory",
  "Statistics",
  "Statistics books",
  "Statistics education",
  "Statistics journals",
  "Stochastic control",
  "Stochastic differential equations",
  "Stochastic models",
  "Stochastic optimization",
  "Stochastic processes",
  "Structural complexity theory",
  "Structures on manifolds",
  "Subgroup properties",
  "Subgroup series",
  "Subharmonic functions",
  "Substructural logic",
  "Summability methods",
  "Summary statistics",
  "Sumsets",
  "Super linear algebra",
  "Surfaces",
  "Surgery theory",
  "Symbolic dynamics",
  "Symmetric functions",
  "Symplectic geometry",
  "Symplectic topology",
  "Systems of formal logic",
  "Systems of probability distributions",
  "Systems of set theory",
  "Systolic geometry",
  "Tails of probability distributions",
  "Tauberian theorems",
  "Tensors",
  "Tensors in general relativity",
  "Ternary operations",
  "Tessellation",
  "Theorems",
  "Theorems in geometry",
  "Theorems in statistics",
  "Theory of continuous functions",
  "Theory of probability distributions",
  "Theta functions",
  "Threefolds",
  "Time series models",
  "Time–frequency analysis",
  "Topological algebra",
  "Topological dynamics",
  "Topological games",
  "Topological graph theory",
  "Topological groups",
  "Topological methods of algebraic geometry",
  "Topological spaces",
  "Topological vector spaces",
  "Topology",
  "Topology of Lie groups",
  "Topology of function spaces",
  "Topology of homogeneous spaces",
  "Topology stubs",
  "Topos theory",
  "Toric sections",
  "Toroidal polyhedra",
  "Traditional mathematics",
  "Transcendental numbers",
  "Transforms",
  "Trees (graph theory)",
  "Trees (set theory)",
  "Triangle geometry",
  "Triangles",
  "Triangles of numbers",
  "Trigonometry",
  "Types of functions",
  "Types of probability distributions",
  "Uniform polyhedra",
  "Uniform spaces",
  "Unitary operators",
  "Unitary representation theory",
  "Units of angle",
  "Universal algebra",
  "Unsolved problems in mathematics",
  "Urelements",
  "Validity (statistics)",
  "Vector bundles",
  "Vector calculus",
  "Vectors (mathematics and physics)",
  "Von Neumann algebras",
  "Wavelets",
  "Wellfoundedness",
  "Zeta and L-functions",
  "Zonohedra",
  "10th-century mathematicians",
  "11th-century mathematicians",
  "12th-century mathematicians",
  "13th-century mathematicians",
  "14th-century mathematicians",
  "15th-century mathematicians",
  "16th-century mathematicians",
  "17th-century mathematicians",
  "18th-century mathematicians",
  "19th-century mathematicians",
  "20th-century mathematicians",
  "21st-century mathematicians",
  "5th-century mathematicians",
  "6th-century mathematicians",
  "7th-century mathematicians",
  "8th-century mathematicians",
  "9th-century mathematicians",
  "Abel Prize laureates",
  "Abel laureates",
  "African mathematicians",
  "Albanian mathematicians",
  "Algebraic geometers",
  "Algebraists",
  "American mathematician stubs",
  "American mathematicians",
  "Ancient Greek mathematicians",
  "Ancient Indian mathematicians",
  "Ancient mathematicians",
  "Argentine mathematicians",
  "Armenian mathematicians",
  "Asian mathematician stubs",
  "Australian mathematicians",
  "Austrian mathematicians",
  "Azerbaijani mathematicians",
  "Belarusian mathematicians",
  "Belgian mathematicians",
  "Bengali mathematicians",
  "Bosnia and Herzegovina mathematicians",
  "Brazilian mathematicians",
  "British mathematicians",
  "Bulgarian mathematicians",
  "Cambridge mathematicians",
  "Cameroonian mathematicians",
  "Canadian mathematicians",
  "Category theorists",
  "Chaos theorists",
  "Chilean mathematicians",
  "Chinese mathematicians",
  "Colombian mathematicians",
  "Combinatorial game theorists",
  "Croatian mathematicians",
  "Cuban mathematicians",
  "Czech mathematicians",
  "Danish mathematicians",
  "David Crighton medalists",
  "Differential geometers",
  "Dutch mathematicians",
  "Egyptian mathematicians",
  "English mathematicians",
  "Estonian mathematicians",
  "European mathematician stubs",
  "Fields Medalists",
  "Finnish mathematicians",
  "French mathematician stubs",
  "French mathematicians",
  "Functional analysts",
  "Geometers",
  "Georgian mathematicians",
  "German mathematician stubs",
  "German mathematicians",
  "Graph theorists",
  "Greek mathematicians",
  "Group theorists",
  "Historians of mathematics",
  "Hong Kong mathematicians",
  "Hungarian mathematicians",
  "Icelandic mathematicians",
  "Indian mathematicians",
  "Iranian mathematicians",
  "Iraqi mathematicians",
  "Irish mathematicians",
  "Israeli mathematicians",
  "Italian mathematician stubs",
  "Italian mathematicians",
  "Japanese mathematicians",
  "Lattice theorists",
  "Latvian mathematicians",
  "Lithuanian mathematicians",
  "Maldivian mathematicians",
  "Mathematical analysts",
  "Mathematical logicians",
  "Mathematician stubs",
  "Mathematicians",
  "Mathematicians by century",
  "Mathematicians by field",
  "Mathematicians by nationality",
  "Mathematicians from Melbourne",
  "Mathematics educators",
  "Measure theorists",
  "Medieval mathematicians",
  "Mexican mathematicians",
  "Model theorists",
  "Moldovan mathematicians",
  "Moroccan mathematicians",
  "New Zealand mathematicians",
  "Nigerian mathematicians",
  "Norwegian mathematicians",
  "Number theorists",
  "Numerical analysts",
  "Operator theorists",
  "Pakistani mathematicians",
  "Palestinian mathematicians",
  "Polish mathematician stubs",
  "Polish mathematicians",
  "Portuguese mathematicians",
  "Probability theorists",
  "Romanian mathematicians",
  "Russian mathematician stubs",
  "Russian mathematicians",
  "Scottish mathematicians",
  "Serbian mathematicians",
  "Set theorists",
  "Sicilian mathematicians",
  "Slovak mathematicians",
  "Slovenian mathematicians",
  "South African mathematicians",
  "Soviet mathematicians",
  "Spanish mathematicians",
  "Sri Lankan mathematicians",
  "Sudanese mathematicians",
  "Swedish mathematicians",
  "Swiss mathematicians",
  "Syrian mathematicians",
  "Taiwanese mathematicians",
  "Tanzanian mathematicians",
  "Topologists",
  "Turkish mathematicians",
  "Ukrainian mathematicians",
  "Uruguayan mathematicians",
  "Vietnamese mathematicians",
  "Welsh mathematicians",
  "Wolf Prize in Mathematics laureates",
  "Women mathematicians",
  "Actuarial associations",
  "Actuarial science",
  "Actuaries",
  "Alan Turing",
  "Algorithms",
  "American actuaries",
  "American cryptographers",
  "American logicians",
  "American statisticians",
  "Analysis of algorithms",
  "Angle",
  "Applicative computing systems",
  "Applied statistics",
  "Archimedes",
  "Aristotle",
  "Article proofs",
  "Articles containing proofs",
  "Artificial life",
  "Astronomical dynamical systems",
  "Australian cryptographers",
  "Australian logicians",
  "Australian statisticians",
  "Austrian cryptographers",
  "Austrian logicians",
  "Automata",
  "Automata theory",
  "Aviation statistics",
  "Ballistics experts",
  "Baseball statistics",
  "Basketball statistics",
  "Bayesian networks",
  "Belgian logicians",
  "Belgian statisticians",
  "Bermuda Triangle",
  "Betting systems",
  "Bioinformatics",
  "Biological theorems",
  "Biostatisticians",
  "Biostatistics",
  "Biostatistics journals",
  "Blaise Pascal",
  "Brahmagupta",
  "Braids",
  "Brazilian logicians",
  "Brazilian statisticians",
  "British actuaries",
  "British cryptographers",
  "British logicians",
  "British statisticians",
  "Bubbles",
  "Buddhist logic",
  "Buildings and structures by shape",
  "Bulgarian logicians",
  "Bulgarian statisticians",
  "Calculators",
  "Canadian actuaries",
  "Canadian statisticians",
  "Celestial coordinate system",
  "Cellular automata",
  "Cellular automata in popular culture",
  "Chaos theory",
  "Character encoding",
  "Charts",
  "Cheminformatics",
  "Chinese logicians",
  "Cipher-machine cryptographers",
  "Cluster analysis",
  "Cluster analysis algorithms",
  "Coin flipping",
  "Comparisons of mathematical software",
  "Computable analysis",
  "Computational models",
  "Computational physics",
  "Computational problems",
  "Computational science",
  "Computer algebra systems",
  "Computer arithmetic",
  "Computer hardware tuning",
  "Computer optimization",
  "Computer science",
  "Computing",
  "Conceptual models",
  "Conservation laws",
  "Constants",
  "Control devices",
  "Control engineering",
  "Control theory",
  "Counting instruments",
  "Critical phenomena",
  "Cross-sectional analysis",
  "Cryptographers",
  "Cryptographers by nationality",
  "Cryptography",
  "Cryptography books",
  "Cryptography contests",
  "Cryptography journals",
  "Cryptography stubs",
  "Cyberneticists",
  "Cybernetics",
  "Czech logicians",
  "Danish statisticians",
  "Data analysis",
  "Data analysis software",
  "Data compression",
  "Data differencing",
  "Data mining",
  "Decision theory",
  "Demographers",
  "Demography",
  "Denotational semantics",
  "Descriptive complexity",
  "Detection theory",
  "Dice",
  "Digital geometry",
  "Digital signal processing",
  "Digital systems",
  "Digital technology",
  "Dimensional analysis",
  "Dimensional instruments",
  "Dimensionless numbers",
  "Documentary television series",
  "Domes",
  "Donald Knuth",
  "Dot patterns",
  "Dutch cryptographers",
  "Dutch logicians",
  "Dutch statisticians",
  "Econometric models",
  "Econometrics",
  "Econometrics journals",
  "Econometrics stubs",
  "Economic data",
  "Economics",
  "Economics curves",
  "Economics theorems",
  "Egyptian cryptographers",
  "Electrodynamics",
  "Encyclopedias of mathematics",
  "English logicians",
  "English statisticians",
  "Entropy",
  "Entropy and information",
  "Equations",
  "Error",
  "Error detection and correction",
  "Estimation theory",
  "Ethics and statistics",
  "Ethnomathematicians",
  "Euclid",
  "Evolutionary algorithms",
  "Exactly solvable models",
  "Experimental design",
  "Fellows of the American Statistical Association",
  "Fiction about cryptography",
  "Fictional dimensions",
  "Fictional mathematicians",
  "Filter theory",
  "Finger-counting",
  "Finite element method",
  "Forensic statistics",
  "Formal languages",
  "Formal methods",
  "Formal specification languages",
  "Frames of reference",
  "Free Bayesian statistics software",
  "French cryptographers",
  "French statisticians",
  "Fundamental constants",
  "Fuzzy logic",
  "GCHQ cryptographers",
  "Game theorists",
  "Game theory",
  "Genetic algorithms",
  "Geographic coordinate systems",
  "Geometric symbol templates",
  "Geostatistics",
  "German logicians",
  "German statisticians",
  "Gottfried Leibniz",
  "Graph data structures",
  "Graph rewriting",
  "Greek logicians",
  "Hamiltonian mechanics",
  "Helices",
  "Hungarian statisticians",
  "Icelandic logicians",
  "Images of fractals",
  "Images of graphs",
  "Index numbers",
  "Indian logicians",
  "Indian statisticians",
  "Information theorists",
  "Information theory",
  "Institute for Advanced Study",
  "Inter-rater reliability",
  "Interactive evolutionary computation",
  "Interactive geometry software",
  "Irish logicians",
  "Irish statisticians",
  "Isaac Newton",
  "Israel Prize in exact science recipients",
  "Israeli cryptographers",
  "Italian cryptographers",
  "Jansenism",
  "Japanese logicians",
  "Japanese statisticians",
  "Jorge Luis Borges",
  "Kerala school of astronomy and mathematics",
  "Knot stubs",
  "Knots",
  "Length",
  "Leonardo da Vinci",
  "Lewis Carroll",
  "Lists of ambiguous numbers",
  "Logic",
  "Logic and statistics",
  "Logic conferences",
  "Logic in computer science",
  "Logic literature",
  "Logic puzzles",
  "Logicians",
  "Logicians by nationality",
  "Lucasian Professors of Mathematics",
  "Luck",
  "M. C. Escher",
  "Machine learning",
  "Machines",
  "Mathematical and quantitative methods (economics)",
  "Mathematical biology",
  "Mathematical chemistry",
  "Mathematical chess problems",
  "Mathematical cognition researchers",
  "Mathematical ecologists",
  "Mathematical economics",
  "Mathematical finance",
  "Mathematical formatting templates",
  "Mathematical function templates",
  "Mathematical markup languages",
  "Mathematical optimization software",
  "Mathematical physicists",
  "Mathematical quantization",
  "Mathematical software",
  "Mathematician templates",
  "Mathematics awards navigational boxes",
  "Mathematics images",
  "Mathematics of music",
  "Mathematics source templates",
  "Mathematics stub templates",
  "Mathematics templates",
  "Mathematics writers",
  "Mechanical calculators",
  "Mechanical puzzles",
  "Mechanics",
  "Members of HM Government Statistical Service",
  "Mental calculators",
  "Meta-analysis",
  "Modal logic",
  "Model checkers",
  "Modern cryptographers",
  "Molecular geometry",
  "Molecular topology",
  "Monte Carlo software",
  "National statistical services",
  "Network performance",
  "Network theory",
  "Network topology",
  "Networks",
  "Neural networks",
  "New Zealand statisticians",
  "Niels Henrik Abel",
  "Noise",
  "Non-equilibrium thermodynamics",
  "Norwegian actuaries",
  "Norwegian demographers",
  "Norwegian statisticians",
  "Number-related lists",
  "Numerical software",
  "Numerology",
  "Nyaya",
  "Operations research",
  "Optimization software",
  "Orientation (geometry)",
  "Oscillation",
  "Pakistani statisticians",
  "Paradoxes",
  "Parity (mathematics)",
  "Paul Erdős",
  "Perspective projection",
  "Pharmaceutical statistics",
  "Philosophers of mathematics",
  "Physics theorems",
  "Pi software",
  "Placeholder names",
  "Polish cryptographers",
  "Polish logicians",
  "Polish statisticians",
  "Polyhedron templates",
  "Population statistics",
  "Potentials",
  "Power laws",
  "Precession",
  "Presidents of statistical organizations",
  "Presidents of the Associação Brasileira de Estatística",
  "Presidents of the Royal Statistical Society",
  "Presidents of the Statistical Society of Canada",
  "Process calculi",
  "Programming language theory stubs",
  "Pseudorandom number generators",
  "Psychometrics",
  "Public-key cryptographers",
  "Putnam Fellows",
  "Pythagorean philosophy",
  "Pythagorean symbols",
  "Pythagoreans",
  "Quantum field theory",
  "Quantum mechanical entropy",
  "Quantum mechanics",
  "Queueing theorists",
  "Queueing theory",
  "Quotas",
  "Randomness",
  "Recreational cryptographers",
  "Recursion",
  "Relational algebra",
  "Relativity",
  "Researchers in geometric algorithms",
  "Risk",
  "Robust statistics",
  "Rotational symmetry",
  "Rubik's Cube",
  "Russian cryptographers",
  "Russian logicians",
  "Russian statisticians",
  "Scaling symmetries",
  "Scientific organizations",
  "Scottish statisticians",
  "Search engine optimization",
  "Second Wranglers",
  "Self-organization",
  "Senior Wranglers",
  "Serialism",
  "Set theoretic programming languages",
  "Signal processing stubs",
  "Social statistics",
  "Sorting algorithms",
  "Spanning tree",
  "Spatial analysis",
  "Spinors",
  "Sports records and statistics",
  "Square One Television",
  "Statistical approximations",
  "Statistical charts and diagrams",
  "Statistical classification",
  "Statistical data agreements",
  "Statistical data coding",
  "Statistical data sets",
  "Statistical data types",
  "Statistical inference",
  "Statistical mechanics",
  "Statistical mechanics theorems",
  "Statistical models",
  "Statistical natural language processing",
  "Statistical organizations",
  "Statistical outliers",
  "Statistical principles",
  "Statistical programming languages",
  "Statistical ratios",
  "Statistical software",
  "Statistician stubs",
  "Statisticians",
  "Statisticians by nationality",
  "Statistics stubs",
  "Statistics-related lists",
  "Stellation diagrams",
  "String metrics",
  "Structural analysis",
  "Sudoku",
  "Supersymmetry",
  "Supertasks",
  "Survival analysis",
  "Swedish information theorists",
  "Swedish statisticians",
  "Swiss statisticians",
  "Symmetry",
  "TeX",
  "Technical drawing",
  "Telephone numbers",
  "Theorem proving software systems",
  "Theoretical biology",
  "Theoretical computer science",
  "Theoretical physics",
  "Theories of deduction",
  "Theory of computation",
  "Thermodynamics",
  "Thomas Carlyle",
  "Tiling puzzles",
  "Time",
  "Time series analysis",
  "Traditional logic",
  "Trees (data structures)",
  "Troff",
  "Turing machine",
  "Type theory",
  "Unified Modeling Language",
  "Units of area",
  "Variables",
  "Variational formalism of general relativity",
  "Volume",
  "Vortices",
  "Warp drive theory",
  "Wave mechanics",
  "Waves",
  "Z notation",
  "Zero (linguistics)"
];